apiVersion: apps/v1
kind: Deployment

metadata:
  name: worker
  namespace: voting-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: worker

  template:
    metadata:
      labels:
        app: worker

    spec:
      imagePullSecrets:
        - name: registry-secret

      containers:
        - name: worker
          image: yamanradan/voting:worker-v1
          imagePullPolicy: IfNotPresent

          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: postgres-secret

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi

          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - grep -aq "Worker.dll" /proc/1/cmdline
            initialDelaySeconds: 10
            periodSeconds: 10
