apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: voting-app-ingress
  namespace: voting-app

spec:
  ingressClassName: nginx

  rules:
    - host: vote.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vote
                port:
                  number: 80

    - host: result.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: result
                port:
                  number: 80
