apiVersion: apps/v1
kind: Deployment

metadata:
  name: vote
  namespace: voting-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: vote

  template:
    metadata:
      labels:
        app: vote

    spec:
      imagePullSecrets:
        - name: registry-secret
      containers:
        - name: vote
          image: yamanradan/voting:vote-v1
          imagePullPolicy: IfNotPresent


          envFrom:
            - configMapRef:
                name: app-config

          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 300m
              memory: 256Mi

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
